spring.application.name=esoterica

spring.datasource.url=jdbc:postgresql://localhost:5432/dbesoterica
spring.datasource.username=postgres
spring.datasource.password=1234

jwt.secret=WnnH3aJrUZa65VPNKtuYMOe4gU0ht12s9wYFl9nCOlL
# Tiempo de vida del token en milisegundos (ej: 86400000 ms = 24 horas)
jwt.expiration=86400000
# Fuerza a Hibernate a comparar las entidades frente a las tablas reales de la BD
spring.jpa.hibernate.ddl-auto=validate

# Opcional pero muy recomendado: Muestra en la consola los detalles del chequeo
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.validate-on-migrate=false

