spring.application.name=esoterica

spring.datasource.url=jdbc:postgresql://localhost:5432/dbesoterica
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none

spring.flyway.validate-on-migrate=false

