spring.application.name=esoteria


# Evitar que Spring Boot intente inicializar el DataSource/Hibernate (sin DB por ahora)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Opcional: desactivar generación automática de DDL si aparece en propiedades
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
