CREATE TABLE ROLE(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL
);

CREATE TABLE USERNAME(
    id SERIAL PRIMARY KEY ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(20),
    password_hash VARCHAR(50),
    first_name VARCHAR(40), 
    last_name VARCHAR(40)
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    role_id INTEGER,

)